name: Deploy ASP.NET Core app to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/eShop-microservices.sln

    - name: Build solution
      run: dotnet build src/eShop-microservices.sln --configuration Release --no-restore

    - name: Publish app
      run: dotnet publish -c Release -o ./publish

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: <YOUR-APP-SERVICE-NAME>
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: ./publish
